name: findmeaserviceprovider
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  shared_preferences: ^0.5.7+3
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+2
  image_cropper: ^1.2.0
  multi_image_picker: ^4.6.7
  filter_list: ^0.0.4
  cupertino_date_textbox: ^1.0.0+3
  rflutter_alert: ^1.0.2
  multilevel_drawer: ^1.0.3
  flutter_speed_dial: ^1.2.5
  flutter_rating_bar: ^3.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/